name: Publish

on:
  workflow_dispatch: {}
  release:
    types: ['created']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: |
          cat > .npmrc << EOF
          //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          EOF
      - run: bun publish --access public
